### ISSUE TITLE
Error starting on 20.6.1

### ISSUE THREAD

**Issue by egadstar** [javajosh/simpatico#11]
> simpatico@0.3.6 start
> node reflector.js

file:///Users/pwashburn/Development/simpatico/core.js:7
const error = msg => {throw new Error(msg)}
                            ^

Error
    at error (file:///Users/pwashburn/Development/simpatico/core.js:7:29)
    at assert (file:///Users/pwashburn/Development/simpatico/core.js:8:51)
    at Object.str (file:///Users/pwashburn/Development/simpatico/core.js:237:23)
    at parseObjectLiteralString (file:///Users/pwashburn/Development/simpatico/core.js:293:6)
    at processConfig (file:///Users/pwashburn/Development/simpatico/reflector.js:69:21)
    at file:///Users/pwashburn/Development/simpatico/reflector.js:33:16
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async loadESM (node:internal/process/esm_loader:42:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

**Comment by javajosh** [comment]
thanks for the report. the problem was that the code didn't deal properly with the no-arg case. You could get around this by with `node reflector.js "{}"`. This problem is fixed with d80d8499095b93e3622b405c3ac41f918fa00e89.
